### PR TITLE
Added language option for company report getting

### PR DESCRIPTION
**Pull request by RomaVan**
Added a possibility to set a language report query param
in the postman API documentary exist such feature. Would be nice to have such one in the library according to get ability change report language. 
A variant with `$company = $client->companies()->get($id . '?language=no');` didn't work acording to way of passing arguments to the Guzzle librarry

### CODE REVIEW

**Comment by Josh-G** [comment]
thanks @RomaVan, is this parameter documented in their API docs somewhere?

**Comment by RomaVan** [comment]
> thanks @RomaVan, is this parameter documented in their API docs somewhere?

yes, I've found this in the postman collection API docs and from Creditsafe support (information about such possibility)
In the postman collection there is request `Company Report Request - Example` and in the params shows this option

I'm sorry, but I cannot find the link where was the exactly this collection documentation

**Review by Josh-G — APPROVED** [review]

**Comment by Josh-G** [comment]
thanks, released as v0.1.4

**Comment by RomaVan** [comment]
Thanks for quick merging

**Pull request merged**
